# Generated by Django 4.2 on 2026-05-02 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laundry', '0004_order_amount_paid_order_paid_at_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('WASH', 'Wash Only'), ('WASH_DRY', 'Wash & Dry'), ('WASH_DRY_FOLD', 'Wash, Dry & Fold'), ('DRY_ONLY', 'Dry Only'), ('DRY_CLEAN', 'Dry Clean'), ('IRON', 'Iron / Press Only'), ('EXPRESS', 'Express Service')], default='WASH_DRY_FOLD', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('WASHING', 'Washing'), ('DRYING', 'Drying'), ('FOLDING', 'Folding / Ironing'), ('READY', 'Ready for Pickup'), ('CLAIMED', 'Claimed')], default='RECEIVED', max_length=20),
        ),
    ]
