# Generated by Django 4.2 on 2026-05-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0018_alter_order_status'),
        ('laundry', '0020_sitesettings_userprofile'),
    ]

    operations = [
    ]
