# Generated by Django 4.2 on 2026-05-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0021_customer_status_contact_length'),
        ('laundry', '0021_merge_20260505_2356'),
    ]

    operations = [
    ]
